name: PHPUnit

on:
  pull_request:
  push:
    branches: [ master ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        php:
          - '8.1'
          - '8.2'
          - '8.3'
          - '8.4'
          - '8.5'
        symfony:
          - '5.4.*' # LTS
          - '6.4.*'
          - '7.4.*'
          - '8.0.*'
        exclude:
          # requires PHP >=8.2
          - php: '8.1'
            symfony: '7.4.*'
          # requires PHP >=8.4
          - php: '8.1'
            symfony: '8.0.*'
          - php: '8.2'
            symfony: '8.0.*'
          - php: '8.3'
            symfony: '8.0.*'

    runs-on: ${{ matrix.os }}

    env:
      SYMFONY: ${{ matrix.symfony }}

    steps:
      - uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          ini-values: date.timezone='UTC'
          tools: composer:v2

      - name: Require symfony
        run: composer --no-update require symfony/symfony:"${SYMFONY}"

      - name: Install dependencies
        run: |
          composer update
          vendor/bin/simple-phpunit install

      - name: Test
        run: |
          composer validate --strict --no-check-lock
          vendor/bin/simple-phpunit --coverage-text --verbose
